service: appointment_scheduler
image: italoaalves/appointment_scheduler

servers:
  web:
    - 129.121.50.44

proxy:
  ssl: true
  host: staging.anella.app

registry:
  server: ghcr.io
  username: italoaalves
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_ENV: staging
    RAILS_LOG_LEVEL: debug

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "appointment_scheduler_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  port: 22022

accessories:
  db:
    image: postgres:17
    host: 129.121.50.44
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: appointment_scheduler
        POSTGRES_DB: appointment_scheduler_staging
      secret:
        - POSTGRES_PASSWORD
    directories:
      - postgres_data:/var/lib/postgresql/data
